#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE}")";

git pull origin master;

function doIt() {
    cd src &&
	rsync --exclude ".git/" \
		--exclude ".DS_Store" \
		--exclude ".osx" \
		-avh --no-perms . ~;
    
    echo '🔗 Creating Symlink for ~/.vscode'

    # Delete the autogenerated settings/keybindings if you opened vscode before the script completed.
    [ -e ~/Library/Application\ Support/Code/User/settings.json ] && rm -rf ~/Library/Application\ Support/Code/User/settings.json
    [ -e ~/Library/Application\ Support/Code/User/keybindings.json ] && rm -rf ~/Library/Application\ Support/Code/User/keybindings.json

    ln -s ~/.vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
    ln -s ~/.vscode/keybindings.json ~/Library/Application\ Support/Code/User/keybindings.json

	# Delete autogenerated spectacle settings if you opened Spectacle before script completed.
	[ -e ~/Library/Application\ Support/Spectacle/Shortcuts.json ] && rm -rf ~/Library/Application\ Support/Spectacle/Shortcuts.json
    ln -s ~/.spectacle ~/Library/Application\ Support/Spectacle/Shortcuts.json

	source ~/.bash_profile;
}

if [ "$1" == "--force" -o "$1" == "-f" ]; then
	doIt;
else
	read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1;
	echo "";
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		doIt;
	fi;
fi;
unset doIt;